CREATE TABLE IF NOT EXISTS {table_name} (
  task_id INTEGER PRIMARY KEY AUTOINCREMENT,
  task VARCHAR(255),
  due_date VARCHAR(255),
  mailaddress VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) 